# Create 1D Array of 0 to 9 

In [45]:
import numpy as np

In [46]:
lst = [0,1,2,3,4,5,6,7,8,9]
a1 = np.array(lst)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Create 2D Array of shape [3][3] with all element as 1

In [47]:
arr1 = np.ones([3,3],order='C')
arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Generate a Numpy array of 15 random integer between 10 and 50

In [48]:
a2 = np.array([10,31,42,33,14,25,16,47,28,19,30,18,27,24,40]).reshape(5,3)
a2 

array([[10, 31, 42],
       [33, 14, 25],
       [16, 47, 28],
       [19, 30, 18],
       [27, 24, 40]])

# Create an array of 5 evenly spaced numbers between 0 and 1(inclusive)

In [49]:
ary = np.linspace(0,1,5)
ary

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Create a 4x4 identity matrix using Numpy

In [50]:
a3 = np.identity(4)
a3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# create an  array from the list[10,20,30,40] and change the datatype to float

In [51]:
Lst = [10,20,30,40]
array = np.array(Lst,dtype=np.float32)
array

array([10., 20., 30., 40.], dtype=float32)

# create a 3x3 array with values from 1 to 9 then extract the 2nd column 

In [52]:
a21 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
a21

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
a22=a21[:,1]
a22

array([2, 5, 8])

# create a 1D array with 10 elements and reshape it into a 2x5 materix

In [54]:
List = [0,1,2,3,4,5,6,7,8,9]
L1 = np.array(lst).reshape(2,5)
L1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# create two 2x2 matrix and perform matrix multiplication

In [55]:
lst = [[1,2],[5,6]]
a1 = np.array(lst)
np.multiply(a1,3)

array([[ 3,  6],
       [15, 18]])

# given the array arr=np.array([5,12,7,18,3]), replace all values greater than 10 with 100

In [56]:
arr = np.array([5, 12, 7, 18, 3])
arr[arr > 10] = 100
arr

array([  5, 100,   7, 100,   3])